check for both names of conman

diff --git a/src/sbin/conman b/src/sbin/conman
--- a/src/sbin/conman
+++ b/src/sbin/conman
@@ -13,5 +13,14 @@ x*)
   ;;
 esac
 
-conpod=$(kubectl -n services get pod -l app.kubernetes.io/name=cray-conman -o jsonpath='{.items[].metadata.name}')
+conpod=$(kubectl -n services get pod -l app.kubernetes.io/name=cray-console-node -o jsonpath='{.items[].metadata.name}') 2> /dev/null
+if [[ -z "$conpod" ]]; then
+    conpod=$(kubectl -n services get pod -l app.kubernetes.io/name=cray-conman -o jsonpath='{.items[].metadata.name}')
+fi
+if [[ -z "$conpod" ]]; then
+    echo "ERROR! conman pod can't be located!"
+    exit 1
+fi
+
+
 exec kubectl -n services exec -it $conpod -c cray-conman -- conman -j ${xname}
