changes from slj to make conman function better querying the console state meneger instead of iterating over all of them

diff --git a/src/sbin/conman b/src/sbin/conman
--- a/src/sbin/conman
+++ b/src/sbin/conman
@@ -1,23 +1,13 @@
 #!/bin/bash
-  
-xname=$(nid2xname $1)
+
+xname=$(/root/bin/nid2xname $1)
 if [[ -z "$xname" ]]; then
   echo "Do not understand $1" 1>&2
   exit 1
 fi
-
-conpods=$(kubectl -n services get pod -l app.kubernetes.io/name=cray-console-node 2> /dev/null | awk '{print $1}')
-CONTAINER=cray-console-node
-if [[ -z "$conpods" ]]; then
-    conpods=$(kubectl -n services get pod -l app.kubernetes.io/name=cray-conman -o jsonpath='{.items[].metadata.name}')
-    CONTAINER=cray-conman
+conpod=$(kubectl -n services exec deploy/cray-console-operator -c cray-console-operator -- /app/get-node ${xname} | jq -r .podname)
+if [ -z "$conpod" ]; then
+  echo "Cannot find console pod for ${xname}" 1>&2
+  exit 1
 fi
-if [[ -z "$conpods" ]]; then
-    echo "ERROR! conman pod can't be located!"
-    exit 1
-fi
-
-for pod in $conpods; do
-    kubectl -n services exec -it $pod -c $CONTAINER -- conman -j ${xname}
-done
-
+exec kubectl -n services exec -it $conpod -c cray-console-node -- conman -j ${xname}
